#!/bin/bash

# Update package list and upgrade all packages
sudo apt-get update
sudo apt-get upgrade -y

# Create odoo user
sudo adduser --system --home=/opt/odoo --group odoo

# Install PostgreSQL
sudo apt-get install -y postgresql

# Create PostgreSQL user
sudo su - postgres -c "createuser --createdb --username postgres --no-createrole --no-superuser --no-password odoo"

# Install dependencies
sudo apt-get install -y python3-pip python3-dev libxml2-dev libxslt1-dev libldap2-dev libsasl2-dev libffi-dev libjpeg-dev libjpeg8-dev zlib1g-dev libssl-dev libpq-dev libtiff5-dev libjpeg8-dev 
libopenjp2-7-dev liblcms2-dev libwebp-dev libharfbuzz-dev libfribidi-dev libxcb1-dev libpq-dev libxml2-dev libxslt1-dev python3-dev 
python3-venv python3-wheel libxslt-dev libzip-dev libldap2-dev libsasl2-dev python3-setuptools node-less python-dateutil
 
# Install and configure wkhtmltopdf
sudo apt-get install -y xfonts-75dpi
wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
sudo apt install -y ./wkhtmltox_0.12.5-1.bionic_amd64.deb

sudo pip3 install --upgrade werkzeug

python3 -c "import werkzeug.contrib"

# Install Odoo
sudo su - odoo -c "git clone --depth 1 --branch 13.0 https://www.github.com/odoo/odoo /opt/odoo/odoo"

# Create and activate virtual environment
sudo su - odoo -c "python3 -m venv /opt/odoo/venv"
sudo su - odoo -c "/opt/odoo/venv/bin/pip install wheel"
sudo su - odoo -c "/opt/odoo/venv/bin/pip install -r /opt/odoo/odoo/requirements.txt"

# Create directory for custom addons
sudo su - odoo -c "mkdir /opt/odoo/custom_addons"

# Create Odoo configuration file
sudo bash -c 'cat > /etc/odoo.conf <<EOF
[options]
; This is the password that allows database operations:
admin_passwd = admin
db_host = False
db_port = False
db_user = odoo
db_password = False
addons_path = /opt/odoo/odoo/addons,/opt/odoo/custom_addons
logfile = /var/log/odoo/odoo.log
EOF'

# Create directory for Odoo logs
sudo mkdir /var/log/odoo
sudo chown odoo: /var/log/odoo

# Create systemd service file for Odoo
sudo bash -c 'cat > /etc/systemd/system/odoo.service <<EOF
[Unit]
Description=Odoo
Documentation=http://www.odoo.com
[Service]
# Ubuntu/Debian convention:
Type=simple
User=odoo
ExecStart=/opt/odoo/venv/bin/python /opt/odoo/odoo/odoo-bin -c /etc/odoo.conf
[Install]
WantedBy=default.target
EOF'

# Reload systemd and start Odoo service
sudo systemctl daemon-reload
sudo systemctl start odoo
sudo systemctl enable odoo

# Print status of Odoo service
sudo systemctl status odoo

echo "Odoo 13 installation and configuration is complete. Access it at http://<your_domain_or_IP_address>:8069"
